name = "sku"
version = "1.0.0"
description = "suffering III"

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
mist = ">= 3.0.0 and < 4.0.0"
gleam_erlang = ">= 0.27.0 and < 1.0.0"
gleam_http = ">= 3.7.0 and < 4.0.0"
gleam_otp = ">= 0.12.1 and < 1.0.0"


[dev-dependencies]
gleeunit = "~> 1.0"
